server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: qiniu-3d-generator
  config:
    name: qiniu-3d-generator-app
  profiles:
    active: dev
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/qiniu_3d_generator?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # Redis配置
  redis:
    host: localhost
    port: 16379
    password: 
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 5000ms
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# MyBatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: org.example.infrastructure.persistent.po
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true

# 注释掉Meshy API配置 - 只保留腾讯混元API
# meshy:
#   api:
#     url: https://api.meshy.ai
#     key: ${MESHY_API_KEY:your_meshy_api_key_here}

# 腾讯云API配置
# 请设置环境变量或在此处配置您的腾讯云密钥
# 环境变量方式（推荐）：
# export TENCENT_SECRET_ID=your_secret_id_here
# export TENCENT_SECRET_KEY=your_secret_key_here
# export TENCENT_REGION=ap-beijing
tencent:
  cloud:
    secret-id: ${TENCENT_SECRET_ID:}
    secret-key: ${TENCENT_SECRET_KEY:}
    region: ${TENCENT_REGION:ap-beijing}
    hunyuan:
      endpoint: ai3d.tencentcloudapi.com
      version: 2025-05-13
      timeout: 60000
      max-retries: 3
      enable-pbr: false
      default-format: OBJ

# API提供商配置 - 只保留腾讯混元
api:
  provider:
    default: hunyuan  # 默认使用腾讯混元
    # 注释掉备用API配置，因为只有一个提供商
    # fallback: hunyuan  # 备用API
    # enable-fallback: true
    enable-fallback: false

# 日志配置
logging:
  level:
    org.example: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/qiniu-3d-generator.log

# 应用自定义配置
app:
  # 缓存配置
  cache:
    default-expire-hours: 168  # 7天
    max-cache-size: 10000
    cleanup-interval: 3600000  # 1小时
  
  # 评估配置
  evaluation:
    auto-evaluate: true
    batch-size: 10
    quality-threshold: 7.0
  
  # 文件存储配置
  storage:
    base-path: /data/3d-models
    max-file-size: 100MB
    allowed-formats: obj,fbx,gltf,glb
  
  # 限流配置
  rate-limit:
    enabled: true
    requests-per-minute: 60
    requests-per-hour: 1000
