server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: qiniu-3d-generator
  config:
    name: qiniu-3d-generator-app
  profiles:
    active: dev
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 5000ms
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# MyBatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: org.example.infrastructure.persistent.po
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true

# 第三方API配置
meshy:
  api:
    url: https://api.meshy.ai
    key: ${MESHY_API_KEY:your_meshy_api_key_here}

# 混元3D API配置
hunyuan:
  api:
    url: http://localhost:7860
    key: ${HUNYUAN_API_KEY:}

# 生成配置
generation:
  api:
    provider: hunyuan  # 可选值: hunyuan, meshy

# 日志配置
logging:
  level:
    org.example: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/qiniu-3d-generator.log

# 应用自定义配置
app:
  # 缓存配置
  cache:
    default-expire-hours: 168  # 7天
    max-cache-size: 10000
    cleanup-interval: 3600000  # 1小时
  
  # 评估配置
  evaluation:
    auto-evaluate: true
    batch-size: 10
    quality-threshold: 7.0
  
  # 文件存储配置
  storage:
    base-path: /data/3d-models
    max-file-size: 100MB
    allowed-formats: obj,fbx,gltf,glb
  
  # 限流配置
  rate-limit:
    enabled: true
    requests-per-minute: 60
    requests-per-hour: 1000
