server:
  port: 8091

spring:
  application:
    name: qiniu-3d-generator-test
  
  # 使用H2内存数据库进行测试
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # 禁用Redis连接
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

# MyBatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: org.example.infrastructure.persistent.po
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 注释掉Meshy API配置（测试环境）- 只保留腾讯混元API
# meshy:
#   api:
#     url: https://api.meshy.ai
#     key: test_key

hunyuan:
  api:
    url: https://hunyuan.tencentcloudapi.com
    secret-id: test_id
    secret-key: test_key
    region: ap-beijing

# API提供商配置 - 只保留腾讯混元
api:
  provider:
    default: hunyuan  # 默认使用腾讯混元
    # 注释掉备用API配置，因为只有一个提供商
    # fallback: hunyuan
    # enable-fallback: true
    enable-fallback: false

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml